export const SITE = {
  routes: {
    home: "/",
    intro: "/intro",
    admissions: "/admissions",
    curriculum: "/curriculum",
    faculty: "/faculty",
    guide: "/guide",
    graduation: "/graduation",
    dualDegree: "/dual-degree",
    exchange: "/exchange",
    gallery: "/gallery",
    news: "/news",
    downloads: "/downloads",
    com: "/college-of-management",
  },
};

export const NAV = [
  {
    key: "intro",
    type: "dropdown",
    items: [
      { key: "intro.about", route: "/intro/about" },
      { key: "intro.highlights", route: "/intro/highlights" },
      { key: "intro.regulations", route: "/intro/regulations" },
      { key: "intro.environment", route: "/intro/environment" },
    ],
  },
  {
    key: "admissions",
    type: "dropdown",
    items: [
      { key: "admissions.mba", route: "/admissions/mba" },
      { key: "admissions.scholarships", route: "/admissions/scholarships" },
      { key: "admissions.international", route: "/admissions/international" },
    ],
  },
  {
    key: "curriculum",
    type: "dropdown",
    items: [
      { key: "curriculum.courses", route: "/curriculum/courses" },
      { key: "curriculum.rules", route: "/curriculum/rules" },
    ],
  },
  { key: "faculty", type: "link", route: "/faculty" },
  { key: "guide", type: "link", route: "/guide" },
  { key: "graduation", type: "link", route: "/graduation" },
  { key: "dualDegree", type: "link", route: "/dual-degree" },
  { key: "exchange", type: "link", route: "/exchange" },
  { key: "gallery", type: "link", route: "/gallery" },
  { key: "news", type: "link", route: "/news" },
  { key: "downloads", type: "link", route: "/downloads" },
  { key: "com", type: "link", route: "/college-of-management" },
];

export const I18N = {
  zh: {
    "nav.menu": "選單",
    "brand.title": "輔仁大學國際經營管理碩士班(imMBA)",
    "brand.subtitle": "Fu Jen Catholic University",
    "top.links.news": "公告",
    "top.links.fju": "輔大連結",
    "top.links.englishSite": "英文網站連結",
    "footer.desc": "輔仁大學管理學院｜國際經營管理碩士班（全英授課）。",
    "footer.contact": "聯絡資訊",
    "footer.phone": "電話",
    "footer.links": "相關連結",
    "search.title": "站內搜尋",
    "search.label": "關鍵字",

    "nav.intro": "簡介",
    "nav.admissions": "招生資訊",
    "nav.curriculum": "課程資訊",
    "nav.faculty": "師資介紹",
    "nav.guide": "imMBA全攻略",
    "nav.graduation": "畢業與離校",
    "nav.dualDegree": "跨國雙碩士",
    "nav.exchange": "海外交換",
    "nav.gallery": "活動集錦",
    "nav.news": "公告",
    "nav.downloads": "表格下載",
    "nav.com": "輔大管理學院",

    "intro.about.title": "簡介｜本班介紹",
    "intro.about.desc": "全英授課、跨文化班級、與產業接軌的國際管理教育。",
    "intro.highlights.title": "簡介｜特色與排名",
    "intro.highlights.desc": "國際合作、跨國雙學位、校友網絡與多元職涯路徑。",
    "intro.regulations.title": "簡介｜本單位規定及辦法",
    "intro.regulations.desc": "修業規範、畢業門檻、論文/專題與學術誠信等事項。",
    "intro.environment.title": "簡介｜學習環境",
    "intro.environment.desc": "國際化校園、資源完善的管理學院與城市便利生活圈。",

    "admissions.mba.title": "招生資訊｜MBA招生資訊",
    "admissions.mba.desc": "申請時程、甄試流程、口試資訊與常見問題。",
    "admissions.scholarships.title": "招生資訊｜獎助學金資訊",
    "admissions.scholarships.desc": "校內外獎助、助學資源、申請資格與注意事項。",
    "admissions.international.title": "招生資訊｜外國學生申請入學",
    "admissions.international.desc": "國際生申請流程、文件清單與英文支援說明。",

    "curriculum.courses.title": "課程資訊｜課程",
    "curriculum.courses.desc": "核心/選修課、學習地圖、與實務專題整合。",
    "curriculum.rules.title": "課程資訊｜課程與修業規則",
    "curriculum.rules.desc": "學分結構、必選修規定、抵免/停修等規則。",

    "pages.faculty.title": "師資介紹",
    "pages.faculty.desc": "跨領域師資陣容：策略、行銷、財務、組織、人資與數據。",
    "pages.guide.title": "imMBA全攻略",
    "pages.guide.desc": "申請、入學、修課、生活到職涯，一站式新生指南。",
    "pages.graduation.title": "畢業與離校",
    "pages.graduation.desc": "畢業門檻、離校程序、文件申請與校友服務。",
    "pages.dualDegree.title": "跨國雙碩士",
    "pages.dualDegree.desc": "與海外名校合作的雙學位路徑與申請要點。",
    "pages.exchange.title": "海外交換",
    "pages.exchange.desc": "交換計畫、合作學校概覽、學分認列與申請流程。",
    "pages.gallery.title": "活動集錦",
    "pages.gallery.desc": "講座、參訪、校園活動與海外學習紀錄。",
    "pages.news.title": "公告",
    "pages.news.desc": "最新消息、招生公告、活動通知與重要提醒。",
    "pages.downloads.title": "表格下載",
    "pages.downloads.desc": "常用表單、申請文件與規章下載。",
    "pages.com.title": "輔大管理學院",
    "pages.com.desc": "管理學院資源、單位連結與學院介紹。",

    "home.kicker": "International Program",
    "home.title": "打造你的全球管理職涯",
    "home.subtitle": "以全英授課與跨文化學習環境，連結國際資源、產業實戰與多元職涯。",
    "home.cta.apply": "立即申請",
    "home.cta.programHighlights": "了解課程特色",
    "home.stat1.value": "100%",
    "home.stat1.label": "English-taught",
    "home.stat2.value": "Dual",
    "home.stat2.label": "Degree pathways",
    "home.stat3.value": "Global",
    "home.stat3.label": "Network & exchange",
    "home.cards.a.title": "招生資訊",
    "home.cards.a.desc": "掌握時程、流程與常見問題，快速完成申請準備。",
    "home.cards.b.title": "課程與修業規則",
    "home.cards.b.desc": "學分結構與學習地圖，讓你清楚規劃每一學期。",
    "home.cards.c.title": "海外合作",
    "home.cards.c.desc": "跨國雙碩士與交換計畫，擴展你的世界版圖。",
    "home.cards.d.title": "活動與公告",
    "home.cards.d.desc": "講座、參訪、校園活動與最新消息一次掌握。",
  },
  en: {
    "nav.menu": "Menu",
    "brand.title": "Fu Jen Catholic University imMBA (International MBA)",
    "brand.subtitle": "College of Management, FJCU",
    "top.links.news": "News",
    "top.links.fju": "FJCU",
    "top.links.englishSite": "English Site",
    "footer.desc":
      "International Master of Business Administration, College of Management, Fu Jen Catholic University.",
    "footer.contact": "Contact",
    "footer.phone": "Phone",
    "footer.links": "Links",
    "search.title": "Site search",
    "search.label": "Keyword",

    "nav.intro": "About",
    "nav.admissions": "Admissions",
    "nav.curriculum": "Curriculum",
    "nav.faculty": "Faculty",
    "nav.guide": "imMBA Guide",
    "nav.graduation": "Graduation",
    "nav.dualDegree": "Dual Degree",
    "nav.exchange": "Exchange",
    "nav.gallery": "Gallery",
    "nav.news": "News",
    "nav.downloads": "Downloads",
    "nav.com": "College of Management",

    "intro.about.title": "About · Program Overview",
    "intro.about.desc": "English-taught, multicultural cohort, and industry-oriented global management education.",
    "intro.highlights.title": "About · Highlights & Recognition",
    "intro.highlights.desc": "International partnerships, dual degrees, alumni network, and diverse career pathways.",
    "intro.regulations.title": "About · Policies & Regulations",
    "intro.regulations.desc": "Study requirements, graduation criteria, thesis/capstone, and academic integrity.",
    "intro.environment.title": "About · Learning Environment",
    "intro.environment.desc": "International campus, strong resources, and convenient city life around Taipei.",

    "admissions.mba.title": "Admissions · MBA Application",
    "admissions.mba.desc": "Timeline, process, interview information, and FAQs.",
    "admissions.scholarships.title": "Admissions · Scholarships",
    "admissions.scholarships.desc": "Funding options, eligibility, and how to apply.",
    "admissions.international.title": "Admissions · International Applicants",
    "admissions.international.desc": "Steps, required documents, and English support.",

    "curriculum.courses.title": "Curriculum · Courses",
    "curriculum.courses.desc": "Core & electives, learning map, and integrated practical projects.",
    "curriculum.rules.title": "Curriculum · Study Rules",
    "curriculum.rules.desc": "Credit structure, requirements, waivers, and policies.",

    "pages.faculty.title": "Faculty",
    "pages.faculty.desc": "Interdisciplinary faculty across strategy, marketing, finance, HR, and analytics.",
    "pages.guide.title": "imMBA Guide",
    "pages.guide.desc": "From application to life and career—your one-stop guide.",
    "pages.graduation.title": "Graduation",
    "pages.graduation.desc": "Graduation requirements, leaving procedures, documents, and alumni services.",
    "pages.dualDegree.title": "Dual Degree",
    "pages.dualDegree.desc": "Partner universities, pathways, and how to apply.",
    "pages.exchange.title": "Exchange",
    "pages.exchange.desc": "Programs, partner schools, credit transfer, and application process.",
    "pages.gallery.title": "Gallery",
    "pages.gallery.desc": "Talks, visits, campus events, and overseas learning moments.",
    "pages.news.title": "News",
    "pages.news.desc": "Announcements, admissions updates, events, and important notices.",
    "pages.downloads.title": "Downloads",
    "pages.downloads.desc": "Frequently used forms and policy documents.",
    "pages.com.title": "College of Management",
    "pages.com.desc": "Resources, links, and an overview of the College of Management.",

    "home.kicker": "International Program",
    "home.title": "Build your global business career",
    "home.subtitle":
      "Learn in an English-taught, multicultural environment—connected to global partners, industry practice, and diverse careers.",
    "home.cta.apply": "Apply Now",
    "home.cta.programHighlights": "Explore program highlights",
    "home.stat1.value": "100%",
    "home.stat1.label": "English-taught",
    "home.stat2.value": "Dual",
    "home.stat2.label": "Degree pathways",
    "home.stat3.value": "Global",
    "home.stat3.label": "Network & exchange",
    "home.cards.a.title": "Admissions",
    "home.cards.a.desc": "Get timelines, steps, and FAQs—prepare your application with clarity.",
    "home.cards.b.title": "Curriculum rules",
    "home.cards.b.desc": "Understand credits and planning—map your semester with confidence.",
    "home.cards.c.title": "Global partnerships",
    "home.cards.c.desc": "Dual degree and exchange opportunities—expand your horizons.",
    "home.cards.d.title": "News & events",
    "home.cards.d.desc": "Stay updated on talks, visits, events, and announcements.",
  },
};

export const NEWS = [
  {
    date: "2026/03/18",
    tag: "Spotlight",
    title_zh: "用同樣的學費，走一段法國的學習歷程",
    title_en: "Study in France with the same tuition—an overseas learning journey",
    route: "/news/2026-03-18-france",
  },
  {
    date: "2026/03/11",
    tag: "Campus",
    title_zh: "上週末的輔大開箱日，你也來逛校園了嗎？",
    title_en: "Did you visit the FJCU open campus day last weekend?",
    route: "/news/2026-03-11-open-campus",
  },
  {
    date: "2026/03/09",
    tag: "Admissions",
    title_zh: "（國際經管-全英MBA）115碩士招生口試通知",
    title_en: "Interview notice for 2026 intake (English-taught MBA)",
    route: "/news/2026-03-09-interview",
  },
  {
    date: "2026/02/09",
    tag: "Admissions",
    title_zh: "（外國學生申請入學）Fall 2026，第二梯次申請：5/1–5/31",
    title_en: "International Applicants (Fall 2026): Round 2 application 5/1–5/31",
    route: "/news/2026-02-09-intl-round2",
  },
];

export function t(lang, key) {
  const pack = I18N[lang] ?? I18N.en;
  return pack[key] ?? I18N.en[key] ?? key;
}

